{{- if and .Values.appsec.tuning.serviceAccount.create .Values.appsec.tuning.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appsec.tuning.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
