apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-appsec-open-appsec-k8s-nginx-ingress-controller
  namespace: choreo-external-ingress-class
spec:
  template:
    spec:
      containers:
      - name: open-appsec
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

