annotations:
  artifacthub.io/changes: |
    - Update Ingress-Nginx version controller-v1.12.3
  artifacthub.io/prerelease: "false"
  openappsec.io/base-chart: https://github.com/kubernetes/ingress-nginx
  openappsec.io/base-chart-version: 4.12.3
apiVersion: v2
appVersion: 1.1.27
description: open-appsec helm chart for Ingress NGINX
home: https://www.openappsec.io
icon: https://downloads.openappsec.io/open-appsec-logo.png
keywords:
- waf
- open-appsec
- ingress
- nginx
kubeVersion: '>=1.21.0-0'
maintainers:
- email: info@openappsec.io
  name: open-appsec Team
name: open-appsec-k8s-nginx-ingress
sources:
- https://github.com/openappsec/openappsec/tree/main/build_system/charts/open-appsec-k8s-nginx-ingress
version: 1.1.27
