
primary:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
metrics:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
appsec:
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
defaultBackend:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  containerSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
controller:
  podSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
  containerSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  admissionWebhooks:
    createSecretJob:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    patchWebhookJob:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    patch:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
  livenessProbe:
    httpGet:
      path: /healthz
      port: 10254
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /healthz
      port: 10254
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3