# rbac:
#   create: true

primary:
  # allowPrivilegeEscalation: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

metrics:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

appsec:
  mode: standalone
  # securityContext:
  #   runAsNonRoot: false
  #   runAsUser: 0
  #   runAsGroup: 0
  #   seccompProfile:
  #     type: RuntimeDefault
  # resources:
  #   requests:
  #     cpu: "100m"
  #     memory: "128Mi"
  #   limits:
  #     cpu: "200m"
  #     memory: "256Mi"
  nginx:
    image:
      repository: "sankalpafernando/openappsec-nginx-attachment"
      tag: "v3"

# defaultBackend:
#   resources:
#     requests:
#       cpu: "100m"
#       memory: "128Mi"
#     limits:
#       cpu: "200m"
#       memory: "256Mi"
  # containerSecurityContext:
  #   runAsNonRoot: false
  #   runAsUser: 0
  #   runAsGroup: 0
  #   seccompProfile:
  #     type: RuntimeDefault

controller:
  # podSecurityContext:
  #   runAsNonRoot: false
  #   runAsUser: 0
  #   runAsGroup: 0
  #   seccompProfile:
  #     type: RuntimeDefault
  # containerSecurityContext:
  #   runAsNonRoot: false
  #   runAsUser: 0
  #   runAsGroup: 0
  #   seccompProfile:
  #     type: RuntimeDefault
  # resources:
  #   requests:
  #     cpu: "100m"
  #     memory: "128Mi"
  #   limits:
  #     cpu: "200m"
  #     memory: "256Mi"
  ingressClass: choreo-external-ingress-class
  ingressClassResource:
    name: choreo-external-ingress-class
    controllerValue: "k8s.io/appsec-nginx"
  extraArgs:
    default-ssl-certificate: "choreo-ingress-controllers/choreo-dev-wildcard-tls-secret"
    configmap: "choreo-ingress-controllers/choreo-external-ingress-controller"
    election-id: "open-appsec-ingress-leader"
    enable-annotation-validation: "true"
    shutdown-grace-period: "30"
  publishService:
    enabled: false
    pathOverride: "choreo-ingress-controllers/choreo-external-ingress-controller"
  annotations:
    checkov.io/skip1: "CKV_K8S_20=Default is set by NIC"
    checkov.io/skip2: "CKV_K8S_38=Default is set by NIC"
    checkov.io/skip3: "CKV_K8S_25=Default is set by NIC"
    checkov.io/skip4: "CKV_K8S_22=Default is set by NIC"
    checkov.io/skip5: "CKV_K8S_40=Default is set by NIC"
    checkov.io/skip6: "CKV_K8S_AZURE_WSO2_2=Default is set by NIC"
  # admissionWebhooks:
    # createSecretJob:
    #   resources:
    #     requests:
    #       cpu: "100m"
    #       memory: "128Mi"
    #     limits:
    #       cpu: "200m"
    #       memory: "256Mi"
    # patchWebhookJob:
    #   resources:
    #     requests:
    #       cpu: "100m"
    #       memory: "128Mi"
    #     limits:
    #       cpu: "200m"
    #       memory: "256Mi"
    # patch:
    #   securityContext:
    #     runAsNonRoot: false
    #     runAsUser: 0
    #     runAsGroup: 0
    #     seccompProfile:
    #       type: RuntimeDefault
  livenessProbe:
    httpGet:
      path: /healthz
      port: 10254
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /healthz
      port: 10254
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
